export const settings = {
    slidePourcentage : document.getElementById('html').offsetWidth,
    pourcentage : 0,
    maxPourcentage : 0 -  document.getElementById('html').offsetWidth,
    minPourcentage : 0,
    articleNumber : 0,
    wwwElement : document.getElementById('www'),
    wwwImageElement : document.getElementById('www_image'),
    pencilElement : document.getElementById('pencil'),
    pencilImageElement : document.getElementById('pencil_image'),
    responsiveElement : document.getElementById('responsive'),
    responsiveImageElement : document.getElementById('responsive_image'),
    rankingElement : document.getElementById('ranking'),
    rankingImageElement : document.getElementById('ranking_image'),
    serviceTitleElement : document.getElementById('service_name'),
    noJsMessageElement : document.getElementById('no_js_message'),
    selectJsEnabledElement : document.getElementById('select_js_enabled'),
    languagesElement : document.getElementById('languages'),
    servicesListLiElements : document.querySelectorAll('#services_list li'),
    contactElement : document.getElementById('contact'),
    buttonElements : document.querySelectorAll("button"),
    firstSliderElement : document.getElementById('first_slider'),
    secondSliderElement : document.getElementById('second_slider'),
    navListLiElements : document.querySelectorAll('#nav_list>li'),
    firstDropdownElement : document.getElementById('first_dropdown'),
    secondDropdownElement : document.getElementById('second_dropdown'),
    thirdDropdownElement : document.getElementById('third_dropdown'),
    fourthDropdownElement : document.getElementById('fourth_dropdown'),
    fifthDropdownElement : document.getElementById('fifth_dropdown'),
    navFirstArrowElement : document.getElementById('nav_first_arrow'),
    navSecondArrowElement : document.getElementById('nav_second_arrow'),
    navThirdArrowElement : document.getElementById('nav_third_arrow'),
    navFourthArrowElement : document.getElementById('nav_fourth_arrow'),
    navFifthArrowElement : document.getElementById('nav_fifth_arrow'),
    firstNavListItemElement : document.getElementById('first_nav_list_item'),
    secondNavListItemElement : document.getElementById('second_nav_list_item'),
    thirdNavListItemElement : document.getElementById('third_nav_list_item'),
    fourthNavListItemElement : document.getElementById('fourth_nav_list_item'),
    fifthNavListItemElement : document.getElementById('fifth_nav_list_item'),
    hobbiesButtonElement : document.getElementById('hobbies_button'),
    hobbiesListElement : document.getElementById('hobbies_list'),
    firstOverlayElement : document.getElementById('overlay'),
    secondOverlayELement : document.getElementById('second_overlay'),
    firstCloseELement : document.getElementById('close1'),
    secondCloseELement : document.getElementById('close2'),
    articleNumberElement : document.getElementById('article_number'),
    articleHoverLiELements : document.querySelectorAll('#article_hover>li:not(:last-child)'),
    articleHoverLastLiELement : document.querySelector('#article_hover>li:last-child'),
    articleHoverElement : document.getElementById('article_hover'),
    basketElement : document.getElementById('basket'),
    deleteArticleElement : document.getElementById('delete_article'),
    backToServicesElement : document.getElementById('back_to_services'),
    languageChosenElement : document.getElementById('language_chosen'),
    selectOptionsElement : document.getElementById('select_options'),
    languagesSponsorsImgElement : document.querySelector('#languages_sponsors img'),
    selectOptionsPElements : document.querySelectorAll('#select_options p'),
    selectJsEnabledImgElement : document.querySelector('#select_js_enabled img'),
    burgerMenuElement : document.getElementById('burger_menu'),
    navListElement : document.getElementById('nav_list'),
    navListAElement : document.querySelectorAll('#nav_list ul li a'),
    noDisplayClass : 'no_display',
    removeNoDisplayClass : 'remove_no_display',
    activeServiceClass : 'active_service',
    aServiceIsActiveClass : 'a_service_is_active',
    rotateClass : 'rotate',
    activeDropdownClass : 'active_dropdown',
    disappearedMiddleLineClass : 'disappeared_middle_line',
    wwwId : 'www',
    pencilId : 'pencil',
    responsiveId : 'responsive',
    firstSliderPreviousId : "first_slider_previous",
    firstSliderNextId : "first_slider_next",
    secondSliderPreviousId : "second_slider_previous",
    firstNavListItemId : 'first_nav_list_item',
    secondNavListItemId : 'second_nav_list_item',
    thirdNavListItemId : 'third_nav_list_item',
    fourthNavListItemId : 'fourth_nav_list_item',
    wwwActivePath : './assets/www_active.svg',
    designActivePath : './assets/design_active.svg',
    responsiveActivePath : './assets/responsive_active.svg',
    referencementActivePath : './assets/referencement_active.svg',
    wwwPath : './assets/www.svg',
    designPath : './assets/design.svg',
    responsivePath : './assets/responsive.svg',
    referencementPath : './assets/referencement.svg',
}